### ISSUE TITLE
Add tests for appointment commands

### ISSUE THREAD

**Issue by Gra7ityIC3** [AY2425S1-CS2103T-F14b-1/tp#133]
### Tasks

- [x] Add tests for `ListAppointmentCommand` (PR #136)
- [ ] Add tests for `AddAppointmentCommand` and `AddAppointmentCommandParser`
- [ ] Add tests for `EditAppointmentCommand` and `EditAppointmentCommandParser`
- [x] Add tests for `DeleteAppointmentCommand` and `DeleteAppointmentCommandParser` (PR #257)
